config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :messages do
    resources :messagecommits
  end

  get 'pages/pourquoi'
  get 'pages/admin'
  get 'pages/messages'
  get 'pages/fonctionnement'
  get 'pages/mentions_legales'
  get 'pages/charte'


  get 'refus_message', to: 'messages#refus_message'
  get 'accept_message', to: 'messages#accept_message'
  get 'refus_messagecommit', to: 'messagecommits#refus_messagecommit'
  get 'accept_messagecommit', to: 'messagecommits#accept_messagecommit'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  has_many :messagecommits, dependent: :destroy
  has_many_attached :photos

end

app/models/messagecommit.rb
class Messagecommit < ApplicationRecord
  belongs_to :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

end

app/controllers/messagecommits_controller.rb
class MessagecommitsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new, :create]

  def new

    @messagecommit = Messagecommit.new
    @messagecommits = Messagecommit.where(message_id: params[:message_id], statut:"yes")
    @message = Message.find(params[:message_id])



  end

  def create

    @messagecommit = Messagecommit.new(messagecommit_params)
    @messagecommit.statut = "standby"
    @messagecommit.traceur = "standby"
    @messagecommit.message_id = params[:message_id]

    if @messagecommit.save
      flash[:notice] = 'Votre commentaire a été soumis à l équipe admin merci !'
      redirect_to new_message_messagecommit_path(params[:message_id])
    else
      flash[:notice] = 'Un problème est survenu ! Si le problème persiste, contactez l équipe'
      redirect_to new_message_messagecommit_path(params[:message_id])
    end

  end

  def index

    @messagecommits = Message.all

  end

  def show

  end

  def destroy

  end

  def accept_messagecommit

    @messagecommit = Messagecommit.find(params[:id])
    @messagecommit.traceur = current_user.id
    @messagecommit.statut = "yes"
    @messagecommit.save
    redirect_to pages_admin_path

  end

  def refus_messagecommit

    @messagecommit = Messagecommit.find(params[:id])
    @messagecommit.traceur = current_user.id
    @messagecommit.statut = "no"
    @messagecommit.save
    redirect_to pages_admin_path


  end

  private

  def messagecommit_params
    params.require(:messagecommit).permit(:content, :traceur, :statut)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

skip_before_action :authenticate_user!, only: [:new, :create]

  def new

    @message = Message.new

  end

  def create

    @message = Message.new(message_params)
    @message.statut = "standby"
    @message.traceur = "standby"
    if @message.save
      flash[:notice] = 'Votre message a été soumis à l équipe admin merci !'
      redirect_to pages_messages_path
    else
      flash[:notice] = 'Un problème est survenu ! Si le problème persiste, contactez l équipe'
      redirect_to pages_message_path
    end

  end

  def index

    @messages = Message.all

  end

  def show

  end

  def destroy

  end

  def accept_message

    @message = Message.find(params[:id])
    @message.traceur = current_user.id
    @message.statut = "yes"
    @message.save
    redirect_to pages_admin_path

  end

  def refus_message

    @message = Message.find(params[:id])
    @message.traceur = current_user.id
    @message.statut = "no"
    @message.save
    redirect_to pages_admin_path

  end

  private

  def message_params
    params.require(:message).permit(:content, :traceur, :statut, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about,:charte, :messages, :pourquoi, :fonctionnement, :mentions_legales]
  def home
  end

  def about
  end

  def charte
  end

  def messages
  end

  def pourquoi
  end

  def admin
  end

  def fonctionnement
  end

  def mentions_legales
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= meta_title %></title>
   <meta name="description" content="<%= meta_description %>">
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1" name="viewport">

   <!-- Facebook Open Graph data -->
   <meta property="og:title" content="<%= meta_title %>" />
   <meta property="og:type" content="website" />
   <meta property="og:url" content="<%= request.original_url %>" />
   <meta property="og:image" content="<%= meta_image %>" />
   <meta property="og:description" content="<%= meta_description %>" />
   <meta property="og:site_name" content="<%= meta_title %>" />

   <!-- Twitter Card data -->
   <meta name="twitter:card" content="summary_large_image">
   <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:title" content="<%= meta_title %>">
   <meta name="twitter:description" content="<%= meta_description %>">
   <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:image:src" content="<%= meta_image %>">

   <link rel="apple-touch-icon" sizes="180x180" href="../assets/apple-icon-180x180.png">
   <link href="../assets/favicon.ico" rel="icon">
   <link href="../assets/main.3f6952e4.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </head>
  <body class="minimal">
    <div id="site-border-left"></div>
    <div id="site-border-right"></div>
    <div id="site-border-top"></div>
    <div id="site-border-bottom"></div>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
   <script type="text/javascript" src="../assets/main.70a66962.js"></script>
</html>

app/views/messagecommits/new.html.erb
<body class="">
  <div id="site-border-left"></div>
  <div id="site-border-right"></div>
  <div id="site-border-top"></div>
  <div id="site-border-bottom"></div>
  <link href="/assets/main.3f6952e4.css" rel="stylesheet">
  <script type="text/javascript" src="/assets/main.70a66962.js"></script>
  <div class=" background-image-container white-text-container" style="background-image: url('https://res.cloudinary.com/dz83jh064/image/upload/v1630962761/fondvierge_shtwyk.png'); background-attachment:local; min-height: 1000px;">
    <div class="section-container">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="section-container-spacer text-center">
              <h1 class="h2">Voir et commenter un message</h1>
              <h3>Chaque commentaire sera modéré pour le moment afin de respecter la charte tout en préservant la liberté d'expression</h3>
            </div>
            <div class="card">
              <div class="card-header" style="background-color:grey;color:black;">Contenu du message publié le <%=@message.created_at.strftime("%d.%m.%Y") %></div>
              <div class="card-body" style="background-color:white;color:black;">
                <% if @message.photos.attached?%>
                  <% @message.photos.each do |photo| %>
                    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                  <% end %>
                <%end%>
                <H3 class="card-text" style="background-color:white;color:black;" ><%=@message.content%></H3>
              </div>
            </div>
            <% @messagecommits.each do |commit|%>
              <div class="card">
                <div class="card-body" style="background-color:white;color:black;">
                  <p class="card-text" style="background-color:white;color:black;" >Publié le <%=commit.created_at.strftime("%d.%m.%Y")%> : <%=commit.content%></p>
                  <% if current_user%>
                    <%= link_to 'Effacer', refus_messagecommit_path(id: commit.id) , class:"btn btn-primary", style:"background-color:grey;color:black;"%>
                  <%end%>
                </div>
              </div>
            <%end%>
            <button class="btn btn-danger" style="background-color:grey;color:black;" id="refresh" onclick="document.location.reload(false)"> Rafraichir la page </button>
            <br>
            <br>
            <%= simple_form_for [@message, @messagecommit], class: 'login-box' do |f| %>
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                  <form action="" class="reveal-content">
                    <div class="row">
                      <div class="col-md-7">
                        <div class="form-group">
                          <%= f.input :content, class: "form-control ", label:false, placeholder:"Écrivez votre commentaire ici", input_html: {style: 'height:100px;'}, required: true %>
                        </div>
                        <button style="background-color:white; color:grey;" type="submit" class="btn btn-default btn-lg">Soumettre à l'équipe</button>
                      </div>
                      <div class="col-md-5 address-container">
                        <ul style="color:white;" class="list-unstyled">
                          <li>
                            <span class="fa-icon">
                              <i style="color:white;" class="fa fa-at" aria-hidden="true"></i>
                            </span>
                            webmaster@moiaussijesuisdentiste.fr
                          </li>
                          <li>
                            <span class="fa-icon">
                              <i style="color:white;" class="fa fa fa-map-marker" aria-hidden="true"></i>
                            </span>
                              Paris
                          </li>
                        </ul>
                        <h3>Suivez-nous sur les réseaux sociaux</h3>
                        <a href="http://www.facebook.com/groups/458865635246428/" title="" class="fa-icon">
                          <i class="fa fa-facebook"></i>
                        </a>
                        <a href="https://twitter.com/jesuisdentiste" title="" class="fa-icon">
                          <i class="fa fa-twitter"></i>
                        </a>
                        <a href="https://www.linkedin.com/in/moiaussi-jesuisdentiste-604b2a220/" title="" class="fa-icon">
                          <i class="fa fa-linkedin"></i>
                        </a>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>


<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

app/views/messagecommits/show.html.erb
<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<div class=" background-image-container white-text-container" style="background-image: url('https://res.cloudinary.com/dz83jh064/image/upload/v1630962761/fondvierge_shtwyk.png'); background-attachment:local; min-height: 1000px;">
<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">Voir et commenter un message</h1>
            <h3>Chaque commentaire sera modéré afin de respecter la charte tout en préservant la liberté d'expression</h3>
          </div>


              <%@message = Message.where(id: params[:message_id])%>
              <%@messagecommits = Messagecommit.where(message_id: @message.last.id) %>
              <%@messagecommit = Messagecommit.new%>


          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <%= simple_form_for [@message, @messagecommit], class: 'login-box' do |f| %>


               <form action="" class="reveal-content">
                  <div class="row">
                    <div class="col-md-7">

                      <div class="form-group">
                        <%= f.input :content, class: "form-control ", label:false, placeholder:"Écrivez votre commentaire ici", input_html: {style: 'height:100px;'}, required: true %>
                      </div>

                      <button style="background-color:white; color:grey;" type="submit" class="btn btn-default btn-lg">Soumettre à l'équipe</button>
                    </div>
                    <div class="col-md-5 address-container">
                      <ul style="color:white;" class="list-unstyled">

                        <li>
                          <span class="fa-icon">
                            <i style="color:white;" class="fa fa-at" aria-hidden="true"></i>
                          </span>
                          moiaussijesuisundentiste@gmail.com
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i style="color:white;" class="fa fa fa-map-marker" aria-hidden="true"></i>
                          </span>
                          Paris
                        </li>
                      </ul>
                      <h3>Suivez-nous sur les réseaux sociaux</h3>
                      <a href="http://www.facebook.com" title="" class="fa-icon">
                        <i class="fa fa-facebook"></i>
                      </a>
                      <a href="http://www.twitter.com" title="" class="fa-icon">
                        <i class="fa fa-twitter"></i>
                      </a>
                      <a href="http://www.linkedin.com" title="" class="fa-icon">
                        <i class="fa fa-linkedin"></i>
                      </a>

                    </div>
                  </div>
                </form>
              <%end%>

            </div>

          </div>

       </div>
      </div>
    </div>
  </div>
</div>



<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

app/views/messages/new.html.erb
<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<div class=" background-image-container white-text-container" style="background-image: url('https://res.cloudinary.com/dz83jh064/image/upload/v1630962761/fondvierge_shtwyk.png'); background-attachment:local; min-height: 1000px;">
<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">03 : Écrire un message</h1>
            <h3>Pour être publiés et afin d'éviter tout dérapage, les messages seront modérés pour le moment par nos admins respectueux de notre charte</h3>
          </div>

          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <%= simple_form_for [@message] do |f| %>

               <form action="" class="reveal-content">
                  <div class="row">
                    <div class="col-md-7">

                      <div class="form-group">
                        <%= f.input :content, class: "form-control ", label:false, placeholder:"Écrivez votre message ici", input_html: {style: 'height:100px;'}, required: true %>
                      </div>
                      <div class="form-group" style="color:white;">

                        <%= f.input :photos, as: :file, input_html: { multiple: true } %>

                      </div>
                      <button style="background-color:white; color:grey;" type="submit" class="btn btn-default btn-lg">Soumettre à l'équipe</button>
                    </div>
                    <div class="col-md-5 address-container">
                      <ul style="color:white;" class="list-unstyled">

                        <li>
                          <span class="fa-icon">
                            <i style="color:white;" class="fa fa-at" aria-hidden="true"></i>
                          </span>
                          webmaster@moiaussijesuisdentiste.fr
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i style="color:white;" class="fa fa fa-map-marker" aria-hidden="true"></i>
                          </span>
                          Paris
                        </li>
                      </ul>
                      <h3>Suivez-nous sur les réseaux sociaux</h3>
                      <a href="http://www.facebook.com/groups/458865635246428/" title="" class="fa-icon">
                        <i class="fa fa-facebook"></i>
                      </a>
                      <a href="https://twitter.com/jesuisdentiste" title="" class="fa-icon">
                        <i class="fa fa-twitter"></i>
                      </a>
                      <a href="https://www.linkedin.com/in/moiaussi-jesuisdentiste-604b2a220/" title="" class="fa-icon">
                        <i class="fa fa-linkedin"></i>
                      </a>

                    </div>
                  </div>
                </form>
              <%end%>

            </div>

          </div>

       </div>
      </div>
    </div>
  </div>
</div>



<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

app/views/pages/admin.html.erb
<body class="">

<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<div class=" background-image-container white-text-container" style="background-image: url('https://res.cloudinary.com/dz83jh064/image/upload/v1630962761/fondvierge_shtwyk.png'); background-attachment:local; min-height: 1000px;">
<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">08 : Espace Admin</h1>
          </div>
          <div class="section-container-spacer text-center">
            <h2 class="h2">Les messages en attente de validation</h2>


          <% @messages = Message.where(statut: "standby")%>
          <% if @messages.length == 0 %>
            <div class="card">
            <div class="card-header" style="background-color:grey;color:black;">
                    #MAJSD</div>
            <div class="card-body" style="background-color:white;color:black;">
            <p class="card-text" style="background-color:white;color:black;" >Pas de messages pour le moment...</p>

            </div>
          </div>
          <% else%>
            <% @messages.each do |mess|%>
            <div class="card">
              <div class="card-header" style="background-color:grey;color:black;">
                    Message publié le <%=mess.created_at.strftime("%d.%m.%Y") %></div>


              <% if mess.photos.attached?%>
                  <% mess.photos.each do |photo| %>
                    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                  <% end %>
              <%end%>




              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" ><%=mess.content%></p>

                <%= link_to 'Accepter',  accept_message_path(id: mess.id) , class:"btn btn-primary" ,style:"background-color:grey;color:black;"%>
                <%= link_to 'Refuser', refus_message_path(id: mess.id) , class:"btn btn-primary", style:"background-color:grey;color:black;"%>

              </div>
            </div>
            <br>
          <%end%>
        <%end%>
</div>
          <div class="section-container-spacer text-center">
            <h2 class="h2">Les commentaires en attente de validation</h2>


          <% @messagecommits = Messagecommit.where(statut: "standby")%>
          <% if @messagecommits.length == 0 %>
            <div class="card">
            <div class="card-header" style="background-color:grey;color:black;">
                    #MAJSD</div>
            <div class="card-body" style="background-color:white;color:black;">
            <p class="card-text" style="background-color:white;color:black;" >Pas de commentaires pour le moment...</p>

            </div>
          </div>
          <% else%>
            <% @messagecommits.each do |mess|%>
            <div class="card">
              <div class="card-header" style="background-color:grey;color:black;">
                    Commentaire publié le <%=mess.created_at.strftime("%d.%m.%Y") %></div>
              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" ><%=mess.content%></p>


                <%= link_to 'Accepter',  accept_messagecommit_path(id: mess.id) , class:"btn btn-primary" ,style:"background-color:grey;color:black;"%>
                <%= link_to 'Refuser', refus_messagecommit_path(id: mess.id) , class:"btn btn-primary", style:"background-color:grey;color:black;"%>


              </div>
            </div>
            <br>
          <%end%>
        <%end%>
        </div>
          <div class="section-container-spacer text-center">
            <h2 class="h2">Activités des membres admin</h2>
            <% @refuscommits = Messagecommit.where(statut: "no")%>
            <% @acceptcommits = Messagecommit.where(statut: "yes")%>
            <% @refusmessages = Message.where(statut: "no")%>
            <% @acceptmessages = Message.where(statut: "yes")%>



            <% if @refuscommits.length == 0%>

            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Pas d'activité pour les refus de commentaires pour le moment...</p>

              </div>
            </div>

            <% else%>

            <% @refuscommits.each do |mess|%>
            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Le membre admin n°<%=mess.traceur%> a refusé le commentaire proposé le <%=mess.created_at.strftime("%d.%m.%Y") %> dont le contenu était : <%=mess.content%></p>

              </div>
            </div>
            <br>
          <%end%>
          <%end%>

          <% if @acceptcommits.length == 0%>

            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Pas d'activité pour les acceptations de commentaires pour le moment...</p>

              </div>
            </div>

          <%else%>

          <% @acceptcommits.each do |mess|%>
            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Le membre admin n°<%=mess.traceur%> a accepté le commentaire proposé le <%=mess.created_at.strftime("%d.%m.%Y") %> dont le contenu était : <%=mess.content%></p>

              </div>
            </div>
            <br>
          <%end%>
          <%end%>

          <% if @refusmessages.length == 0%>

            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Pas d'activité pour les refus de messages pour le moment...</p>

              </div>
            </div>

          <%else%>

          <% @refusmessages.each do |mess|%>
            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Le membre admin n°<%=mess.traceur%> a refusé le message proposé le <%=mess.created_at.strftime("%d.%m.%Y") %> dont le contenu était : <%=mess.content%></p>

              </div>
            </div>
            <br>
          <%end%>
          <%end%>

          <% if @acceptmessages.length == 0%>

            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Pas d'activité pour les acceptations de messages pour le moment...</p>

              </div>
            </div>


          <%else%>

          <% @acceptmessages.each do |mess|%>
            <div class="card">

              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" >Le membre admin n°<%=mess.traceur%> a accepté le message proposé le <%=mess.created_at.strftime("%d.%m.%Y") %> dont le contenu était : <%=mess.content%></p>

              </div>
            </div>
            <br>
          <%end%>
          <%end%>


          </div>


      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/messages.html.erb
<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<div class=" background-image-container white-text-container" style="background-image: url('https://res.cloudinary.com/dz83jh064/image/upload/v1630962761/fondvierge_shtwyk.png'); background-attachment:local; min-height: 1000px;">
<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">02 : Les messages</h1>
            <h3>Ici vous trouverez l'ensemble des messages de la plateforme</h3>
          </div>
          <% @messages = Message.where(statut: "yes")%>
          <% if @messages.length == 0 %>
            <div class="card">
            <div class="card-header" style="background-color:grey;color:black;">
                    #MAJSD</div>
            <div class="card-body" style="background-color:white;color:black;">
            <p class="card-text" style="background-color:white;color:black;" >Pas de messages pour le moment...</p>

            </div>
          </div>



          <% else%>
            <% @messages.each do |mess|%>
            <div class="card">
              <div class="card-header" style="background-color:grey;color:black;">
                    Message publié le <%=mess.created_at.strftime("%d.%m.%Y") %></div>
              <div class="card-body" style="background-color:white;color:black;">
                <p class="card-text" style="background-color:white;color:black;" ><%=mess.content%></p>
                <p class="card-text" style="background-color:white;color:black;" >Nombre de commentaires= <%= Messagecommit.where(message_id: mess.id, statut:"yes").count%>  Nombre de photos attachées= <%=mess.photos.count%></p>


                <%= link_to 'Voir le message et commenter',  new_message_messagecommit_path(mess.id) , class:"btn btn-primary" ,style:"background-color:grey;color:black;"%>
                <% if current_user%>
                <%= link_to 'Effacer',  refus_message_path(id: mess.id) , class:"btn btn-primary" ,style:"background-color:grey;color:black;"%>
                <%end%>
              </div>
            </div>
            <br>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar  navbar-fixed-top navbar-inverse">
    <div class="container">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="<%=root_path%>" title="">01 : Accueil</a></li>
          <li><a href="<%=pages_messages_path%>" title="">02 : Les messages</a></li>
          <li><a href="<%=new_message_path%>" title="">03 : Écrire un message</a></li>
          <li><a href="<%=pages_pourquoi_path%>" title="">04 : Pourquoi #MAJSD</a></li>
          <li><a href="<%=pages_fonctionnement_path%>" title="">05 : Notre fonctionnement</a></li>
          <li><a href="<%=pages_charte_path%>" title="">06 : Notre charte de modération</a></li>
          <li><a href="<%=pages_mentions_legales_path%>" title="">07 : Mentions légales</a></li>
          <li><a href="<%=pages_admin_path%>" title="">08 : Espace Admin</a></li>
          <% if current_user.present?%>
            <li><a href="<%=destroy_user_session_path%>" title="">09 : Déconnexion</a></li>
          <%end%>
        </ul>
      </div>
    </div>
  </nav>
</header>